@baseUrl=http://localhost:3001/api
@resourceName=products

# Products

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###

# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?price_gte=300

###

# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?name_like=tasty


###

# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=12

###

# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=desc


###

# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
		"categoryId": "3",
		"name": "White Classic Sneakers",
		"categories": "shoes",
		"brands": "vans",
		"description": "We love the dramatic ruffle details down the sleeve, delicate fabric buttons and polished cuffs.",
		"image": "https://zonex.famithemes.com/wp-content/uploads/2019/05/sneaker-768x768.jpg",
		"price": 40,
		"featured": true
}

###

# @name update
PATCH {{baseUrl}}/{{resourceName}}/KkSXxPt
Content-Type: application/json

{
	"name": "Tasty Plastic Chips Update",
	"price": 950
}

###

# @name remove
DELETE {{baseUrl}}/{{resourceName}}/2
